### ISSUE TITLE
why are there Pirates in my .less files, when I tell it to only hook for .js and .jsx?

### ISSUE THREAD

**Issue by Pomax** [ariporad/pirates#15]
I'm using the following code:
```
var pirates = require("pirates");
var babel = require("babel-core");

var loaders = {
  latex: require('../lib/latex-loader'),
  pre: require('../lib/pre-loader'),
  p: require('../lib/p-loader'),
  babel: function(source) {
    return babel.transform(source, {
      presets: ['es2015', 'react']
    }).code;
  }
};

function convert(source, filename) {
  source = loaders.p(source);
  source = loaders.pre(source);
  source = loaders.latex(source);
  source = loaders.babel(source);
  return source;
}

module.exports = pirates.addHook(convert, { exts: ['.js','.jsx'] });
```

however, this generates the following log:
```
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\components\sections\catmullmoulding\index.js
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\components\sections\polybezier\index.js
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\components\sections\shapes\index.js
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\components\sections\projections\index.js
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\components\sections\offsetting\index.js
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\components\sections\graduatedoffset\index.js
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\components\sections\circles\index.js
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\components\sections\circles_cubic\index.js
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\components\sections\arcapproximation\index.js
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\components\Navigation.jsx
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\components\Navigation.jsx
J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\stylesheets\style.less

J:\Junctions\Users\Mike\Documents\Git projects\projects\BezierInfo-2\node_modules\babel-core\lib\transformation\file\index.js:548
      throw err;
      ^

SyntaxError: unknown: Unexpected token (1:11)
```

Which... well, is odd. Why are there pirates all over my `.less` file? That shouldn't even make it in, it has no `.js` or `.jsx` extension. Yes, I'm `require()`ing them, but they don't match the file extension, so why is pirates treating them as match?

**Comment by ariporad** [comment]
Hmm... That's strange. Do you have an example project I could look at?

**Comment by Pomax** [comment]
Yep: hit up https://thimble.mozilla.org/projects/24971/remix and download the project to see this in action as minimal reproducible example.

**Comment by ariporad** [comment]
Oh, yeah, that would be a bug. I'll get a patch out ASAP.

**Comment by Pomax** [comment]
:+1:

**Comment by ariporad** [comment]
@Pomax: Can you confirm that this is fixed in v2.1.1.

**Comment by Pomax** [comment]
hmm, it looks like I'm still seeing pirates trying to parse `less` files even though the only extension it's allowed to hook for is `jsx`:
```
C:\Users\Mike\Documents\Git projects\temp\_>npm install pirates
C:\Users\Mike\Documents\Git projects\temp\_
├── pirates@2.1.1
└── UNMET PEER DEPENDENCY webpack@^1.0.0

npm WARN EPEERINVALID babel-loader@6.2.1 requires a peer of webpack@^1.0.0 but none was installed.
npm WARN EPACKAGEJSON _ No description
npm WARN EPACKAGEJSON _ No repository field.
npm WARN EPACKAGEJSON _ No license field.

C:\Users\Mike\Documents\Git projects\temp\_>node test
J:\Junctions\Users\Mike\Documents\Git projects\temp\_\App.jsx
J:\Junctions\Users\Mike\Documents\Git projects\temp\_\Page.jsx
J:\Junctions\Users\Mike\Documents\Git projects\temp\_\test.less:1
(function (exports, require, module, __filename, __dirname) { div {
                                                                  ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (J:\Junctions\Users\Mike\Documents\Git projects\temp\_\Page.jsx:5:13)
    at Module._compile (module.js:398:26)
    at Module.fakeCompile [as _compile] (J:\Junctions\Users\Mike\Documents\Git projects\temp\_\node_modules\pirates\lib\index.js:63:26)
```

**Comment by Pomax** [comment]
wait, no, that could just be babel. let me do a test with pirates hooking into the .less extension and blanking it.

**Comment by Pomax** [comment]
fun finding while trying, this:
```
function convertJS(source, filename) {
  console.log(filename);
  return "";
}
```
Causes Pirates to report that the function returned a non-string, which is not technically true. It coerces to false, but it's still a string =)

**Comment by ariporad** [comment]
@Pomax: Hmm... I'll fix that. Is the extensions thing fixed though?

**Comment by ariporad** [comment]
@Pomax: Actually, I think that's not a bug. Having a module be an empty string should be a warning.

**Comment by Pomax** [comment]
I'm using the following hook code now:
```
var pirates = require("pirates");
var babel = require("babel-core");

var loaders = {
  babel: function(source) {
    return babel.transform(source, {
      presets: ['es2015', 'react']
    }).code;
  }
};

function convertJS(source, filename) {
  console.log("JS(X) FOUND: " + filename);
  return loaders.babel(source);
}

function convertLESS(source, filename) {
  console.log("LESS found: " + filename);
  return "module.exports = {};";
}

var hooks = [
  pirates.addHook(convertJS, { exts: ['.js', '.jsx']}),
  pirates.addHook(convertLESS, { exts: ['.less'] })
];

module.exports = function unhook() {
  hooks.forEach(function(h) { h.unhook(); });
};
```
Which logs this:
```
JS(X) FOUND: J:\Junctions\Users\Mike\Documents\Git projects\temp\_\App.jsx
JS(X) FOUND: J:\Junctions\Users\Mike\Documents\Git projects\temp\_\App.jsx
JS(X) FOUND: J:\Junctions\Users\Mike\Documents\Git projects\temp\_\Page.jsx
JS(X) FOUND: J:\Junctions\Users\Mike\Documents\Git projects\temp\_\Page.jsx
LESS found: J:\Junctions\Users\Mike\Documents\Git projects\temp\_\test.less
```
Suggesting that the filtering for the extension is partly fixed, but also still partly broken: `js`/`jsx` hooks no longer parse LESS, but a hook set up with one handler for multiple extensions still fires more than once for a file.

**Comment by Pomax** [comment]
@ariporad yeah it's definitely *wrong* to return an empty string, so Pirates is right to throw a warning/error, but the error message needs a tweak, since an empty string is still a string.

**Comment by Pomax** [comment]
Using this code:
```
var hooks = [
  pirates.addHook(convertJS, { exts: ['.js']}),
  pirates.addHook(convertJS, { exts: ['.jsx']}),
  pirates.addHook(convertLESS, { exts: ['.less'] })
];
```
So with separate bindings for JS and JSX, despite using the same handler, results in this log:
```
JS(X) FOUND: J:\Junctions\Users\Mike\Documents\Git projects\temp\_\App.jsx
JS(X) FOUND: J:\Junctions\Users\Mike\Documents\Git projects\temp\_\Page.jsx
LESS found: J:\Junctions\Users\Mike\Documents\Git projects\temp\_\test.less
```
So it looks like it's just `ext` parsing causing a handler to be called as many times as there are extensions bound to it, rather than shortcutting after the first hit.

**Comment by ariporad** [comment]
@Pomax: Does the `fix/matcher-called-multiple-times` branch fix this?

**Comment by Pomax** [comment]
yep, looks like it!
```
var hooks = [
  pirates.addHook(convertJS, { exts: ['.js', '.jsx']}),
  pirates.addHook(convertLESS, { exts: ['.less'] })
];
```
log:
```
C:\Users\Mike\Documents\Git projects\temp\_>node test.js
JS(X) FOUND: J:\Junctions\Users\Mike\Documents\Git projects\temp\_\App.jsx
JS(X) FOUND: J:\Junctions\Users\Mike\Documents\Git projects\temp\_\Page.jsx
LESS found: J:\Junctions\Users\Mike\Documents\Git projects\temp\_\test.less
```
no more duplicates

**Comment by ariporad** [comment]
YAY!!

**Comment by ariporad** [comment]
Ok, should be fixed, and in v2.1.1.

**Comment by Pomax** [comment]
awesome work @ariporad!
